// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0h6ea39GMz_jaqVfCfV2BkhRUJMYt4Dg',
    appId: '1:27276041104:web:58da1f983fb28ec2a4f115',
    messagingSenderId: '27276041104',
    projectId: 'testingapp-77a3c',
    authDomain: 'testingapp-77a3c.firebaseapp.com',
    storageBucket: 'testingapp-77a3c.appspot.com',
    measurementId: 'G-834Z0VV5RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnFHHJOM0iV_rTsuZ9lEgIvm5qrm0PKQw',
    appId: '1:27276041104:android:a31bbb6597670f85a4f115',
    messagingSenderId: '27276041104',
    projectId: 'testingapp-77a3c',
    storageBucket: 'testingapp-77a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbR8QGeOy8ABUQI_hoHUQ5GYRdKuyDwyw',
    appId: '1:27276041104:ios:2ac087c70b084d17a4f115',
    messagingSenderId: '27276041104',
    projectId: 'testingapp-77a3c',
    storageBucket: 'testingapp-77a3c.appspot.com',
    iosBundleId: 'com.example.deliveryapptesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbR8QGeOy8ABUQI_hoHUQ5GYRdKuyDwyw',
    appId: '1:27276041104:ios:2ecd35a46231f94ca4f115',
    messagingSenderId: '27276041104',
    projectId: 'testingapp-77a3c',
    storageBucket: 'testingapp-77a3c.appspot.com',
    iosBundleId: 'com.example.deliveryapptesting.RunnerTests',
  );
}
